// File generated by Studio Bot.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for iOS - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macOS - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for Windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for Linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCPa6IxwtEFZeRn9KYPQESFyOD2XdcYVk',
    appId: '1:44703752154:web:cc79d8456eab705c24eae3',
    messagingSenderId: '44703752154',
    projectId: 'ticketing-system-3ad55',
    authDomain: 'ticketing-system-3ad55.firebaseapp.com',
    storageBucket: 'ticketing-system-3ad55.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbtbuT-nBjiymrre7xNcS-PWXj3Uh0wyc',
    appId: '1:44703752154:android:b56288621e648c4b24eae3',
    messagingSenderId: '44703752154',
    projectId: 'ticketing-system-3ad55',
    storageBucket: 'ticketing-system-3ad55.firebasestorage.app',
  );
}
