// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'Web is not supported by this generated file. Run `flutterfire configure` to generate options.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'Android is not supported by this generated file. Run `flutterfire configure` to generate options.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'iOS is not supported by this generated file. Run `flutterfire configure` to generate options.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'macOS is not supported by this generated file. Run `flutterfire configure` to generate options.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'Windows is not supported by this generated file. Run `flutterfire configure` to generate options.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'Linux is not supported by this generated file. Run `flutterfire configure` to generate options.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }
}
